dependencies:
  - name: postgresql
    version: 0.8.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.install
  - name: exposecontroller
    version: 2.3.55
    repository: http://chartmuseum.build.cd.jenkins-x.io
    alias: gitea-expose
  - name: exposecontroller
    version: 2.3.55
    repository: http://chartmuseum.build.cd.jenkins-x.io
    alias: gitea-cleanup
