apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gitea.gitea.fullname" . }}
  labels:
    app: {{ template "gitea.gitea.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  postgresql-user: {{ .Values.postgresql.postgresUser | b64enc | quote }}
