apiVersion: v1
data:
{{- if .Values.Master.DockerConfig }}
  .dockerconfigjson: {{ .Values.Master.DockerConfig | b64enc | quote }}
{{- else }}
  .dockerconfigjson: ""
{{- end }}
kind: Secret
metadata:
  name: master-jenkins-docker-cfg
type: "kubernetes.io/dockerconfigjson"